const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"Content-Type, Authorization","access-control-allow-methods":"GET,POST,OPTIONS"}});
const sha256=async s=>{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")};
const token=()=>crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");
async function userFromReq(env,req){const a=req.headers.get("Authorization")||"",t=a.startsWith("Bearer ")?a.slice(7):"";if(!t)return null;return await env.DB.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>? AND u.enabled=1").bind(t,Date.now()).first()}
export default {async fetch(req,env){if(req.method==="OPTIONS")return json({ok:true});const p=new URL(req.url).pathname;try{
if(p==="/api/health")return json({ok:true});
if(p==="/api/auth/register"&&req.method==="POST"){const b=await req.json(),email=String(b.email||"").trim().toLowerCase(),name=String(b.name||email).trim(),pw=String(b.password||"");if(!email||pw.length<8)return json({error:"Email и пароль минимум 8 символов обязательны"},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Аккаунт уже существует"},409);const id=crypto.randomUUID(),role=email===String(env.ADMIN_EMAIL||"").trim().toLowerCase()?"admin":"user",enabled=role==="admin"?1:0;await env.DB.prepare("INSERT INTO users VALUES(?,?,?,?,?,?,?)").bind(id,email,name,await sha256(pw),role,enabled,Date.now()).run();if(!enabled)return json({error:"Регистрация выполнена. Доступ должен разрешить администратор."},403);const t=token();await env.DB.prepare("INSERT INTO sessions VALUES(?,?,?)").bind(t,id,Date.now()+2592000000).run();return json({token:t,user:{id,email,name,role,enabled:true}})}
if(p==="/api/auth/login"&&req.method==="POST"){const b=await req.json(),email=String(b.email||"").trim().toLowerCase(),pw=String(b.password||"");const x=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!x||x.password_hash!==await sha256(pw))return json({error:"Неверный email или пароль"},401);if(!x.enabled)return json({error:"Доступ к приложению закрыт администратором"},403);const t=token();await env.DB.prepare("INSERT INTO sessions VALUES(?,?,?)").bind(t,x.id,Date.now()+2592000000).run();return json({token:t,user:{id:x.id,email:x.email,name:x.name,role:x.role,enabled:true}})}
if(p==="/api/auth/me"){const x=await userFromReq(env,req);if(!x)return json({error:"Не авторизован"},401);return json({user:{id:x.id,email:x.email,name:x.name,role:x.role,enabled:true}})}
if(p==="/api/auth/logout"){const a=req.headers.get("Authorization")||"",t=a.startsWith("Bearer ")?a.slice(7):"";if(t)await env.DB.prepare("DELETE FROM sessions WHERE token=?").bind(t).run();return json({ok:true})}
if(p==="/api/admin/users"){const x=await userFromReq(env,req);if(!x||x.role!=="admin")return json({error:"Требуются права администратора"},403);const r=await env.DB.prepare("SELECT id,email,name,role,enabled,created_at FROM users ORDER BY created_at DESC").all();return json({users:r.results})}
const m=p.match(/^\/api\/admin\/users\/([^/]+)\/status$/);if(m&&req.method==="POST"){const x=await userFromReq(env,req);if(!x||x.role!=="admin")return json({error:"Требуются права администратора"},403);const b=await req.json();await env.DB.prepare("UPDATE users SET enabled=? WHERE id=?").bind(b.enabled?1:0,m[1]).run();if(!b.enabled)await env.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(m[1]).run();return json({ok:true})}
return json({error:"Not found"},404)}catch(e){return json({error:String(e?.message||e)},500)}}}
